---
title: "Orange vs Sosh"
author: "Famibelle Médhi"
date: "Monday, March 16, 2015"
output: html_document
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
library(dygraphs)
library(xts)
library(xlsx)

facebook.insight.Sosh <- read.xlsx(
    file = "../../../Downloads/Facebook Insights Data Export (Post Level) - Sosh - 2015-03-16.xlsx",
    sheetIndex = 1,
    startRow = 3, 
    header = FALSE
)

facebook.insight.colTitle.Sosh <- read.xlsx2(
    file = "../../../Downloads/Facebook Insights Data Export (Post Level) - Sosh - 2015-03-16.xlsx",
    sheetIndex = 1,
    startRow = 1, 
    endRow = 2,
    stringsAsFactors = FALSE
)

facebook.insight.Orange <- read.xlsx(
    file = "../../../Downloads/Facebook Insights Data Export (Post Level) - Orange - 2015-03-16.xlsx",
    sheetIndex = 1,
    startRow = 3, 
    header = FALSE
)

facebook.insight.colTitle.Orange <- read.xlsx2(
    file = "../../../Downloads/Facebook Insights Data Export (Post Level) - Orange - 2015-03-16.xlsx",
    sheetIndex = 1,
    startRow = 1, 
    endRow = 2,
    stringsAsFactors = FALSE
)


colnames(facebook.insight.Sosh) <- colnames(facebook.insight.colTitle.Sosh)
colnames(facebook.insight.Orange) <- colnames(facebook.insight.colTitle.Orange)

facebook.insight.TimeSerie.Sosh     <- xts(facebook.insight.Sosh[,-7],   order.by = facebook.insight.Sosh$Posted,   tzone = "CET")
facebook.insight.TimeSerie.Orange   <- xts(facebook.insight.Orange[,-7], order.by = facebook.insight.Orange$Posted, tzone = "CET")

facebook.insight <- cbind(facebook.insight.TimeSerie.Orange[,8], facebook.insight.TimeSerie.Sosh[,8])
colnames(facebook.insight) <- c("Orange.Lifetime.Post.organic.reach", "Sosh.Lifetime.Post.organic.reach")

```
### Reach Organique des publications de la page Facebook Orange France
```{r echo=FALSE}
dygraph(facebook.insight.TimeSerie.Orange[,8], group = "Organic") %>%
    dySeries(name = "Lifetime.Post.organic.reach", label = "Orange Organic Reach") %>%
    dyLegend(show = "always", hideOnMouseOut = TRUE) %>%
    dyOptions(animatedZooms = TRUE, labelsKMB = TRUE, logscale = FALSE, stepPlot = TRUE, colors = "#FF6600") %>%
    dyRangeSelector(keepMouseZoom = TRUE)

```

### Reach Organique des publications de la page Facebook Sosh
``` {r echo=FALSE}
dygraph(facebook.insight.TimeSerie.Sosh[,8],   group = "Organic") %>%
    dySeries(name = "Lifetime.Post.organic.reach", label = "Sosh Organic Reach") %>%
    dyLegend(show = "always", hideOnMouseOut = TRUE) %>%
    dyOptions(animatedZooms = TRUE, labelsKMB = TRUE, logscale = FALSE, stepPlot = TRUE) %>%
    dyRangeSelector(keepMouseZoom = TRUE)

```


```{r echo=FALSE}
suppressPackageStartupMessages(library(googleVis))
library(googleVis)

Cal.Orange <- gvisCalendar(
    facebook.insight.Orange, 
    datevar="Posted", 
    numvar="Lifetime.Post.organic.reach",
    chartid = "OrangeCalendrier",
    options=list(
        title="Orange France Daily Reach",
#         height=1024, width=1200,
        calendar="{yearLabel: { fontName: 'Times-Roman',
                        fontSize: 32, color: '#FF6600', bold: true},
                        cellSize: 20,
                        cellColor: { stroke: 'red', strokeOpacity: 0.2 },
                        focusedCellColor: {stroke:'red'}}")
    )

Cal.Sosh <- gvisCalendar(
    facebook.insight.Sosh, 
    datevar="Posted", 
    numvar="Lifetime.Post.organic.reach",
    chartid = "SoshCalendrier",
    options=list(
        title="Sosh France Daily Reach",
#         height=1024, width=1200,
        calendar="{yearLabel: { fontName: 'Times-Roman',
        fontSize: 32, color: '#1A8763', bold: true},
        cellSize: 20,
        cellColor: { stroke: 'red', strokeOpacity: 0.2 },
        focusedCellColor: {stroke:'red'}}")
    )

Calendrier <- gvisMerge(Cal.Orange, Cal.Sosh, horizontal = FALSE) 
plot(Calendrier)


```
### Reach Moyen par jour de la semaine
### Reach Moyen par semaine

